services:
  db:
    container_name: orservice_db
    env_file: ".env"
    restart: on-failure
    image: postgres:latest
    ports:
      - "5432:5432"
    networks:
      orservice:
        - ipv4_address: 10.10.2.2
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test:
        ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
  wt:
    image: containrrr/watchtower
    labels:
      - "com.centurylinklabs.watchtower.scope=orservice"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 --scope orservice

volumes:
  postgres-data:

networks:
  orservice:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.2.0/24
          gateway: 10.10.2.1