services:
  db:
    container_name: orservice_db
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orderservice_db
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}