services:
  db:
    container_name: orservice_db
    restart: always
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file: ".env"
    environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    logging:
      options:
        max-size: "10m"
        max-file: "3"