name: Build verification
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Setup Docker and docker-compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          cp .env.example .env
      - name: Start postgres with docker-compose
        run: docker-compose up -d
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: '3.8.6'
      - name: Build with Maven
        run: mvn clean install

  dependency-submission:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Generate and submit dependecy graph
        uses: advanced-security/maven-dependency-submission-action@v4
